language: julia
os:
  - linux
 # - osx
# branches:
#   except:
#     - 0.7
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: nightly
  
notifications:
  email:
    on_success: never
    on_failure: always
